# Generated by Django 2.2.4 on 2019-12-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AddField(
            model_name='profile',
            name='userId',
            field=models.IntegerField(default=None),
        ),
    ]
