# Generated by Django 2.2.4 on 2019-12-31 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gram', '0002_auto_20191230_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='images',
            name='profile',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='images',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='images',
            name='userId',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='followers',
            name='insta',
            field=models.CharField(default='', max_length=50),
        ),
    ]
